-- =============================================
-- Lina - V5: Atualizar dados a partir de JSON
-- =============================================

DELETE FROM item_cardapio;
DELETE FROM refeicao_informacao_nutricional;
DELETE FROM refeicao_periodos_permitidos;
DELETE FROM refeicao_restricoes;
DELETE FROM refeicao_ingrediente;
DELETE FROM refeicao;
DELETE FROM ingrediente;

INSERT INTO ingrediente (id, nome, categoria) VALUES (1, 'Ovo', 'PROTEINAS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (2, 'Tomate', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (3, 'Cebola', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (4, 'Pimentão', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (5, 'Azeite', 'OUTROS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (6, 'Iogurte', 'LATICINIOS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (7, 'Banana', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (8, 'Chia', 'GRAOS_E_CEREAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (9, 'Goma de Tapioca', 'GRAOS_E_CEREAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (10, 'Queijo', 'LATICINIOS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (11, 'Leite', 'LATICINIOS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (12, 'Aveia', 'GRAOS_E_CEREAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (13, 'Frango', 'PROTEINAS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (14, 'Arroz', 'GRAOS_E_CEREAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (15, 'Salada (mix)', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (16, 'Carne Bovina', 'PROTEINAS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (17, 'Batata Doce', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (18, 'Filé de Peixe', 'PROTEINAS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (19, 'Legumes (mix)', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (20, 'Castanhas (mix)', 'OUTROS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (21, 'Maçã', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (22, 'Pasta de Amendoim', 'OUTROS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (23, 'Frutas (mix)', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (24, 'Granola', 'GRAOS_E_CEREAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (25, 'Folhas Verdes', 'FRUTAS_E_VEGETAIS');
INSERT INTO ingrediente (id, nome, categoria) VALUES (26, 'Sal', 'OUTROS');

INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (1, 220, 10, '1. Quebre os ovos em uma tigela. 2. Bata até ficar homogêneo. 3. Aqueça o azeite. 4. Refogue os legumes. 5. Adicione os ovos. 6. Cozinhe até firmar. 7. Sirva.', 'https://drive.google.com/file/d/1_Ezukv-5cm4KP1Vkbt12edARQL0G5Ial/view', 'Omelete com Legumes');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (2, 180, 5, '1. Coloque o iogurte na tigela. 2. Corte a banana. 3. Adicione ao iogurte. 4. Acrescente a chia. 5. Misture e sirva.', 'https://drive.google.com/file/d/1sPEt72SQp0cY81djkZhKvxP6_C-kdth8/view', 'Iogurte com Frutas');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (3, 250, 8, '1. Aqueça a frigideira. 2. Espalhe a tapioca. 3. Aguarde firmar. 4. Adicione o queijo. 5. Dobre. 6. Sirva.', 'https://drive.google.com/file/d/1xbpzD1MHC_SXImYsgqHgbkPPBJnbuavP/view', 'Tapioca com Queijo');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (4, 210, 5, '1. Corte a banana. 2. Coloque no liquidificador. 3. Adicione leite e aveia. 4. Bata por 1 minuto. 5. Sirva.', 'https://drive.google.com/file/d/1wc5PpPl1EETnd0yv-W6Mofp8Jq1fdzFC/view', 'Vitamina de Banana');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (5, 400, 25, '1. Tempere o frango. 2. Grelhe por 5-7 min cada lado. 3. Cozinhe o arroz. 4. Prepare a salada. 5. Monte o prato.', 'https://drive.google.com/file/d/18bwglLwymT2CDWrW-GWzGmf40Cd4TrlN/view', 'Frango com Arroz');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (6, 420, 30, '1. Corte a batata. 2. Cozinhe por 15 min. 3. Tempere a carne. 4. Grelhe por 4-6 min. 5. Sirva.', 'https://drive.google.com/file/d/1iSHlmxPhQ8XIUnKj-7Kox3xPRbgWrzwk/view', 'Carne com Batata Doce');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (7, 350, 25, '1. Tempere o peixe. 2. Corte os legumes. 3. Coloque na assadeira. 4. Asse por 20 min. 5. Sirva.', 'https://drive.google.com/file/d/1hYujTnTz0EhqvL-EJUP0aXFEutFRLbi1/view', 'Peixe com Legumes');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (8, 300, 15, '1. Bata os ovos. 2. Refogue os legumes. 3. Adicione os ovos. 4. Cozinhe até firmar. 5. Sirva.', 'https://drive.google.com/file/d/1G3cxbOC3MS8Yh2K7OyTBr6VtDrKINKhC/view', 'Omelete Completo');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (9, 180, 2, '1. Separe a porção. 2. Consuma diretamente.', 'https://drive.google.com/file/d/1ERAcJaNs6Z0xzorqEHWgsWNOIt4ctx7H/view', 'Mix de Castanhas');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (10, 200, 5, '1. Lave a maçã. 2. Corte em fatias. 3. Retire o miolo. 4. Adicione a pasta. 5. Sirva.', 'https://drive.google.com/file/d/1lnjo9eASvPaQBBUhK_bl_JKWdgl_mWIK/view', 'Maçã com Pasta');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (11, 160, 5, '1. Corte as frutas. 2. Coloque no liquidificador. 3. Adicione o líquido. 4. Bata. 5. Sirva.', 'https://drive.google.com/file/d/10xrajIIZXlZ0SH7CMHc9QZfIF6qlBAbB/view', 'Smoothie');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (12, 250, 30, '1. Corte o frango. 2. Corte os legumes. 3. Coloque tudo na panela. 4. Cozinhe 25 min. 5. Ajuste o sal.', 'https://drive.google.com/file/d/1yJf67bps2unA6zyLX9DQi-OfG_0gZBzw/view', 'Sopa');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (13, 280, 15, '1. Lave as folhas. 2. Prepare a proteína. 3. Misture tudo. 4. Tempere. 5. Sirva.', 'https://drive.google.com/file/d/1fSQt8DKz7Tgmc5XPxGsIIpMRa8hbIHOD/view', 'Salada Proteica');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (14, 220, 10, '1. Quebre os ovos. 2. Bata bem. 3. Aqueça a frigideira. 4. Despeje os ovos. 5. Cozinhe até firmar. 6. Sirva.', 'https://drive.google.com/file/d/1X9gyPVxuzZQfx-gLtfeczgF4Gak8lZ5e/view', 'Omelete Leve');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (15, 240, 10, '1. Aqueça a frigideira. 2. Espalhe a tapioca. 3. Aguarde firmar. 4. Adicione o recheio. 5. Dobre. 6. Sirva.', 'https://drive.google.com/file/d/1gSkrQ47_kbBUoY33DxaSOSuwOKd8TnPw/view', 'Tapioca com Recheio');
INSERT INTO refeicao (id, calorias, tempo_preparo, modo_preparo, imagem_url, nome) VALUES (17, 190, 3, '1. Coloque o iogurte. 2. Adicione a granola. 3. Misture. 4. Sirva.', 'https://drive.google.com/file/d/1hut_9swLkrZGknZJwThhwnF5x8oohyqS/view', 'Iogurte com Granola');

INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (1, 2, 1, 1, 'unidades');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (2, 0.5, 2, 1, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (3, 0.25, 3, 1, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (4, 0.25, 4, 1, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (5, 1, 5, 1, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (6, 1, 26, 1, 'pitada');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (7, 1, 6, 2, 'pote');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (8, 1, 7, 2, 'unidade');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (9, 1, 8, 2, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (10, 2, 9, 3, 'colheres');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (11, 1, 10, 3, 'fatia');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (12, 1, 7, 4, 'unidade');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (13, 200, 11, 4, 'ml');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (14, 2, 12, 4, 'colheres');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (15, 100, 13, 5, 'g');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (16, 0.5, 14, 5, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (17, 1, 15, 5, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (18, 1, 5, 5, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (19, 100, 16, 6, 'g');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (20, 1, 17, 6, 'unidade');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (21, 1, 18, 7, 'filé');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (22, 1, 19, 7, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (23, 1, 5, 7, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (24, 3, 1, 8, 'unidades');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (25, 0.5, 19, 8, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (26, 1, 5, 8, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (27, 30, 20, 9, 'g');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (28, 1, 21, 10, 'unidade');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (29, 1, 22, 10, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (30, 1, 23, 11, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (31, 200, 11, 11, 'ml');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (32, 100, 13, 12, 'g');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (33, 1, 19, 12, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (34, 1, 26, 12, 'pitada');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (35, 1, 25, 13, 'xícara');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (36, 100, 13, 13, 'g');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (37, 1, 5, 13, 'colher');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (38, 2, 1, 14, 'unidades');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (39, 1, 26, 14, 'pitada');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (40, 2, 9, 15, 'colheres');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (41, 1, 6, 17, 'pote');
INSERT INTO refeicao_ingrediente (id, quantidade, ingrediente_id, refeicao_id, unidade) VALUES (42, 2, 24, 17, 'colheres');

INSERT INTO refeicao_informacao_nutricional (refeicao_id, porcoes, porcao_label, calorias, proteina_g, carboidratos_g, fibras_g, acucares_g, gordura_total_g, gordura_saturada_g, gordura_monoinsaturada_g, gordura_poliinsaturada_g, colesterol_mg, sal_g, sodio_mg, potassio_mg) VALUES (1, 1, 'Para 1 porção', 198, 4.9, 21.5, 4.2, 3.9, 10.1, 2.3, 2, 4.1, 1, 0.1, 28.6, 173.3);

INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (1, 'CAFE_DA_MANHA');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (2, 'CAFE_DA_MANHA');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (3, 'CAFE_DA_MANHA');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (4, 'CAFE_DA_MANHA');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (5, 'ALMOCO');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (6, 'ALMOCO');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (7, 'ALMOCO');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (8, 'ALMOCO');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (9, 'LANCHE_DA_TARDE');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (10, 'LANCHE_DA_TARDE');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (11, 'LANCHE_DA_TARDE');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (17, 'LANCHE_DA_TARDE');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (12, 'JANTAR');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (13, 'JANTAR');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (14, 'JANTAR');
INSERT INTO refeicao_periodos_permitidos (refeicao_id, periodos_permitidos) VALUES (15, 'JANTAR');

INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (1, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (2, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (2, 'LACTOSE');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (3, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (3, 'LACTOSE');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (4, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (4, 'LACTOSE');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (5, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (5, 'VEGETARIANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (6, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (6, 'VEGETARIANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (7, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (7, 'VEGETARIANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (8, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (17, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (17, 'LACTOSE');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (12, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (12, 'VEGETARIANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (13, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (14, 'VEGANO');
INSERT INTO refeicao_restricoes (refeicao_id, restricoes) VALUES (15, 'VEGANO');

SELECT setval('ingrediente_id_seq', (SELECT MAX(id) FROM ingrediente));
SELECT setval('refeicao_id_seq', (SELECT MAX(id) FROM refeicao));
SELECT setval('refeicao_ingrediente_id_seq', (SELECT MAX(id) FROM refeicao_ingrediente));
